import os
import base64
import pyperclip
import discord
import random
import re
import time
from discord.ext import commands
from colorama import Fore
from tqdm import tqdm, trange
from time import sleep


def clear(): return os.system('cls') if os.name == 'nt' else os.system('clear')
os.system("mode con cols=60 lines=20")




clear()
token = input('Welcome To Tommys Hour Counter! Please Enter Your Token Here: ')




class counter(discord.Client):
    async def on_ready(self):
        os.system(f'title [Hour Counter] | Connected As: {self.user}')
            

        clear()
        print(f""" \u001b[31m
╦ ╦╔═╗╦ ╦╦═╗  ╔═╗╔═╗╦ ╦╔╗╔╔╦╗╔═╗╦═╗
╠═╣║ ║║ ║╠╦╝  ║  ║ ║║ ║║║║ ║ ║╣ ╠╦╝
╩ ╩╚═╝╚═╝╩╚═  ╚═╝╚═╝╚═╝╝╚╝ ╩ ╚═╝╩╚═ 
------------------------------------------------------------
               """)

    async def on_message(self, x):
        if 'start' in x.content.lower() and x.author == self.user:
            print('Hours Started')
            time.sleep(3600)
            await x.channel.send('1')
            time.sleep(3600)
            await x.channel.send('2') 
            time.sleep(3600)
            await x.channel.send('3')
            time.sleep(3600)
            await x.channel.send('4')
            time.sleep(3600)
            await x.channel.send('5')
            time.sleep(3600)
            await x.channel.send('6')
            time.sleep(3600)
            await x.channel.send('7')
            time.sleep(3600)
            await x.channel.send('8')
            time.sleep(3600)
            await x.channel.send('9')
            time.sleep(3600)
            await x.channel.send('10')
            time.sleep(3600)
            await x.channel.send('11')
            time.sleep(3600)
            await x.channel.send('12')
            time.sleep(3600)
            await x.channel.send('13')
            time.sleep(3600)
            await x.channel.send('14')
            time.sleep(3600)
            await x.channel.send('15')
            time.sleep(3600)
            await x.channel.send('16')
            time.sleep(3600)
            await x.channel.send('17')
            time.sleep(3600)
            await x.channel.send('18')
            time.sleep(3600)
            await x.channel.send('19')
            time.sleep(3600)
            await x.channel.send('20')
            time.sleep(3600)
            await x.channel.send('21')
            time.sleep(3600)
            await x.channel.send('22')
            time.sleep(3600)
            await x.channel.send('23')
            time.sleep(3600)
            await x.channel.send('24')
            time.sleep(3600)
            await x.channel.send('25')
            time.sleep(3600)
            await x.channel.send('26')
            time.sleep(3600)
            await x.channel.send('27')
            time.sleep(3600)
            await x.channel.send('28')
            time.sleep(3600)
            await x.channel.send('29')
            time.sleep(3600)
            await x.channel.send('30')
            time.sleep(3600)
            await x.channel.send('31')
            time.sleep(3600)
            await x.channel.send('32')
            time.sleep(3600)
            await x.channel.send('33')
            time.sleep(3600)
            await x.channel.send('34')
            time.sleep(3600)
            await x.channel.send('35')
            time.sleep(3600)
            await x.channel.send('36')
            time.sleep(3600)
            await x.channel.send('37')
            time.sleep(3600)
            await x.channel.send('38')
            time.sleep(3600)
            await x.channel.send('39')
            time.sleep(3600)
            await x.channel.send('40')
            time.sleep(3600)
            await x.channel.send('41')
            time.sleep(3600)
            await x.channel.send('42')
            time.sleep(3600)
            await x.channel.send('43')
            time.sleep(3600)
            await x.channel.send('44')
            time.sleep(3600)
            await x.channel.send('45')
            time.sleep(3600)
            await x.channel.send('46')
            time.sleep(3600)
            await x.channel.send('47')
            time.sleep(3600)
            await x.channel.send('48')
            time.sleep(3600)
            await x.channel.send('49')
            time.sleep(3600)
            await x.channel.send('50')
            time.sleep(3600)
            await x.channel.send('51')
            time.sleep(3600)
            await x.channel.send('52')
            time.sleep(3600)
            await x.channel.send('53')
            time.sleep(3600)
            await x.channel.send('54')
            time.sleep(3600)
            await x.channel.send('55')
            time.sleep(3600)
            await x.channel.send('56')
            time.sleep(3600)
            await x.channel.send('57')
            time.sleep(3600)
            await x.channel.send('58')
            time.sleep(3600)
            await x.channel.send('59')
            time.sleep(3600)
            await x.channel.send('60')
            time.sleep(3600)
            await x.channel.send('61')
            time.sleep(3600)
            await x.channel.send('62')
            time.sleep(3600)
            await x.channel.send('63')
            time.sleep(3600)
            await x.channel.send('64')
            time.sleep(3600)
            await x.channel.send('65')
            time.sleep(3600)
            await x.channel.send('66')
            time.sleep(3600)
            await x.channel.send('67')
            time.sleep(3600)
            await x.channel.send('68')
            time.sleep(3600)
            await x.channel.send('69')
            time.sleep(3600)
            await x.channel.send('70')
            time.sleep(3600)
            await x.channel.send('71')
            time.sleep(3600)
            await x.channel.send('72')
            time.sleep(3600)
            await x.channel.send('73')
            time.sleep(3600)
            await x.channel.send('74')
            time.sleep(3600)
            await x.channel.send('75')
            time.sleep(3600)
            await x.channel.send('76')
            time.sleep(3600)
            await x.channel.send('77')
            time.sleep(3600)
            await x.channel.send('78')
            time.sleep(3600)
            await x.channel.send('79')
            time.sleep(3600)
            await x.channel.send('80')
            time.sleep(3600)
            


client = counter()
client.run(token, bot=False)
